# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lessons.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lessons(object):
    def setupUi(self, lessons):
        lessons.setObjectName("lessons")
        lessons.resize(331, 75)
        self.centralwidget = QtWidgets.QWidget(lessons)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        lessons.setCentralWidget(self.centralwidget)

        self.retranslateUi(lessons)
        QtCore.QMetaObject.connectSlotsByName(lessons)

    def retranslateUi(self, lessons):
        _translate = QtCore.QCoreApplication.translate
        lessons.setWindowTitle(_translate("lessons", "Посещения занятий"))
        self.label.setText(_translate("lessons", "TextLabel"))
